# The configuration for Bors-NG, our github merge queue.
#
# https://bors.tech/documentation/reference/

status = [
  "ci/circleci"
]

block_labels = [
  "do not merge"
]

pr_status = [ ]

# timeout after 1 minute
timeout_sec = 60

delete_merged_branches = true

required_approvals = 1
